"use client";

import Link from "next/link";
import Image from "next/image";
import { useImperium } from "@/context/ImperiumContext";
import { StatusChip, TrackChip, Button, EmptyState, Reveal } from "@/components/ui";
import { trackImage } from "@/lib/media";
import {
  trackName, venueName, venue, fmtTime, fmtMoney, shortDay, displayStatus,
  STATUS_META, DAY_LABELS, isClashing,
} from "@/lib/derive";

/* ------------------------------ Event card ----------------------------- */
export function EventCard({ event, showDay = true }) {
  const { now, mode, results } = useImperium();
  const status = displayStatus(event, now, mode, results);
  const img = trackImage(event.trackId);

  return (
    <Link
      href={`/events/${event.slug}`}
      className="group block bg-surface border border-line rounded-lg overflow-hidden transition-all duration-150 ease-imp hover:border-line-strong hover:-translate-y-0.5 focus-visible:border-magenta"
    >
      <div className="relative h-[128px] overflow-hidden bg-elevated">
        <Image
          src={img.src}
          alt=""
          fill
          sizes="(min-width: 1024px) 25vw, (min-width: 640px) 50vw, 100vw"
          className="object-cover transition-transform duration-500 ease-imp group-hover:scale-[1.08]"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-surface via-surface/10 to-transparent" />
        <div className="absolute top-3 left-3"><StatusChip status={status} /></div>
        <div className="absolute top-3 right-3"><TrackChip className="bg-bg/70 backdrop-blur-sm">{trackName(event.trackId)}</TrackChip></div>
      </div>

      <div className="p-5">
        <h3 className="font-display text-[19px] font-bold leading-snug mb-1.5 group-hover:text-magenta transition-colors duration-150">
          {event.name}
          {event.changed && (
            <span className="ml-2 align-middle inline-flex items-center h-5 px-2 rounded-xs bg-closing/[0.15] text-closing text-[10px] font-semibold uppercase tracking-wider">
              Changed
            </span>
          )}
        </h3>
        <p className="text-[14px] text-ink-3 leading-relaxed mb-4 line-clamp-2">{event.shortDescription}</p>

        <div className="flex flex-wrap items-center gap-x-3 gap-y-1.5 text-[13px] text-ink-2 pt-3.5 border-t border-line">
          {showDay && <span>{shortDay(event.date)}</span>}
          <span aria-hidden="true" className="text-ink-dis">·</span>
          <span>{fmtTime(event.startTime)}</span>
          <span aria-hidden="true" className="text-ink-dis">·</span>
          <span>{event.format === "team" ? `Teams of ${event.teamSizeMin}–${event.teamSizeMax}` : "Individual"}</span>
          {event.prizeTotal > 0 && (
            <>
              <span aria-hidden="true" className="text-ink-dis">·</span>
              <span className="text-ink font-semibold tabular-nums">{fmtMoney(event.prizeTotal)}</span>
            </>
          )}
        </div>
      </div>
    </Link>
  );
}

export function EventCardGrid({ events, empty }) {
  if (!events.length) return empty || <EmptyState title="No events match these filters" />;
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 lg:gap-6">
      {events.map((e, i) => (
        <Reveal key={e.id} delay={Math.min(i, 8) * 0.04}>
          <EventCard event={e} />
        </Reveal>
      ))}
    </div>
  );
}

/* ---------------------------- Announcements ---------------------------- */
const PRIORITY = {
  urgent: { border: "border-danger/50", bg: "bg-danger/[0.08]", label: "Urgent", text: "text-danger" },
  important: { border: "border-closing/40", bg: "bg-closing/[0.07]", label: "Important", text: "text-closing" },
  info: { border: "border-line", bg: "bg-surface", label: "Update", text: "text-ink-3" },
};

export function AnnouncementItem({ announcement: a, compact }) {
  const p = PRIORITY[a.priority] || PRIORITY.info;
  const { eventById } = useImperium();
  const ev = a.eventId ? eventById(a.eventId) : null;
  const time = new Date(a.publishedAt).toLocaleString("en-IN", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" });

  return (
    <article className={`border ${p.border} ${p.bg} rounded-md p-4`}>
      <div className="flex items-center gap-2 mb-1.5 flex-wrap">
        <span className={`text-[10px] font-semibold uppercase tracking-[0.08em] ${p.text}`}>{p.label}</span>
        {a.autoGenerated && (
          <span className="text-[10px] font-semibold uppercase tracking-[0.08em] text-magenta border border-magenta/40 rounded-xs px-1.5 py-0.5">
            Auto-generated
          </span>
        )}
        <span className="text-[12px] text-ink-3 ml-auto tabular-nums">{time}</span>
      </div>
      <h3 className="font-semibold text-[15px] mb-1">{a.title}</h3>
      {!compact && <p className="text-[14px] text-ink-2 leading-relaxed">{a.body}</p>}
      {ev && (
        <Link href={`/events/${ev.slug}`} className="inline-block mt-2 text-[13px] text-magenta hover:underline">
          {ev.name} →
        </Link>
      )}
    </article>
  );
}

/* ------------------------------- Schedule ------------------------------ */
export function ScheduleList({ events, highlightClashes = false, allMine = [] }) {
  if (!events.length) return <EmptyState title="Nothing scheduled" body="No events fall on this day." />;

  return (
    <ol className="space-y-3">
      {events.map((e) => {
        const clash = highlightClashes && isClashing(e, allMine);
        return (
          <li key={e.id}>
            <Link
              href={`/events/${e.slug}`}
              className={`flex gap-4 bg-surface border rounded-md p-4 transition-colors duration-150 hover:border-line-strong ${
                clash ? "border-closing/60" : "border-line"
              }`}
            >
              <div className="shrink-0 w-[68px] tabular-nums">
                <div className="text-[15px] font-semibold">{fmtTime(e.startTime)}</div>
                <div className="text-[12px] text-ink-3">{fmtTime(e.endTime)}</div>
              </div>
              <div className="min-w-0 flex-1">
                <h3 className="font-semibold text-[15px] leading-snug mb-1 truncate">{e.name}</h3>
                <p className="text-[13px] text-ink-3">
                  {venueName(e.venueId)} · {trackName(e.trackId)}
                </p>
                {clash && (
                  <p className="mt-2 text-[13px] text-closing flex items-center gap-1.5">
                    <span aria-hidden="true">⚠</span> Overlaps another event you added
                  </p>
                )}
                {e.changed && (
                  <p className="mt-2 text-[13px] text-magenta flex items-center gap-1.5">
                    <span aria-hidden="true">●</span> Updated by organisers
                  </p>
                )}
              </div>
            </Link>
          </li>
        );
      })}
    </ol>
  );
}

/* ------------------------------ Campus map ----------------------------- */
export function CampusMap({ activeVenueId, onSelect }) {
  const { venues } = useImperium();
  return (
    <div className="bg-surface border border-line rounded-lg p-3 sm:p-4">
      <svg viewBox="0 0 600 420" className="w-full h-auto" role="img" aria-label="Illustrative map of the MDI Gurgaon campus showing Imperium venues">
        <rect x="0" y="0" width="600" height="420" fill="#0A0A0F" />
        {/* paths */}
        <path d="M60 200 H540" stroke="#2A2A38" strokeWidth="14" strokeLinecap="round" />
        <path d="M300 60 V380" stroke="#2A2A38" strokeWidth="14" strokeLinecap="round" />
        <path d="M120 320 H480" stroke="#1E1E28" strokeWidth="10" strokeLinecap="round" />
        {/* blocks */}
        <rect x="140" y="120" width="180" height="130" rx="8" fill="#14141C" stroke="#2A2A38" />
        <text x="150" y="140" fill="#7A7A92" fontSize="11">Academic Block</text>
        <rect x="380" y="150" width="130" height="90" rx="8" fill="#14141C" stroke="#2A2A38" />
        <text x="390" y="170" fill="#7A7A92" fontSize="11">Management Block</text>
        <rect x="70" y="300" width="120" height="90" rx="8" fill="#14141C" stroke="#2A2A38" />
        <text x="80" y="320" fill="#7A7A92" fontSize="11">Sports Block</text>
        <rect x="420" y="280" width="130" height="90" rx="8" fill="#14141C" stroke="#2A2A38" />
        <text x="430" y="300" fill="#7A7A92" fontSize="11">Library</text>
        {/* pins */}
        {venues.map((v, i) => {
          const active = v.id === activeVenueId;
          return (
            <g
              key={v.id}
              transform={`translate(${v.x},${v.y})`}
              onClick={() => onSelect && onSelect(v.id)}
              style={{ cursor: onSelect ? "pointer" : "default" }}
            >
              <circle r="14" fill={active ? "#FF2D77" : "#1E1E28"} stroke={active ? "#FF2D77" : "#3D3D4E"} strokeWidth="2" />
              <text textAnchor="middle" y="4.5" fontSize="12" fontWeight="700" fill={active ? "#fff" : "#B4B4C8"}>
                {i + 1}
              </text>
            </g>
          );
        })}
      </svg>

      <ol className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-1.5">
        {venues.map((v, i) => (
          <li key={v.id}>
            <button
              type="button"
              onClick={() => onSelect && onSelect(v.id)}
              className={`w-full text-left flex items-start gap-2.5 min-h-[44px] py-2 px-2.5 rounded-sm transition-colors duration-150 ${
                v.id === activeVenueId ? "bg-magenta/[0.12] text-magenta" : "text-ink-2 hover:bg-elevated"
              }`}
            >
              <span className="shrink-0 w-5 h-5 rounded-full bg-elevated text-[11px] font-bold flex items-center justify-center text-ink-2 mt-0.5">
                {i + 1}
              </span>
              <span className="text-[13px] leading-snug">
                <span className="font-medium text-ink">{v.name}</span>
                <span className="block text-ink-3">{v.note}</span>
              </span>
            </button>
          </li>
        ))}
      </ol>
      <p className="mt-3 text-[12px] text-ink-3">
        Illustrative campus layout for the prototype. A static SVG is deliberate — it loads instantly, works offline and needs no location permission.
      </p>
    </div>
  );
}

/* ------------------------------ Pass card ------------------------------ */
export function PassCard({ participant, onExpandQr }) {
  return (
    <div className="relative bg-gradient-to-br from-elevated to-surface border border-magenta/30 rounded-xl p-6 shadow-glow overflow-hidden">
      <div aria-hidden="true" className="absolute -top-16 -right-16 w-48 h-48 rounded-full bg-magenta/10 blur-3xl" />
      <div className="relative">
        <div className="flex items-start justify-between gap-4 mb-6">
          <div>
            <div className="text-[10px] uppercase tracking-[0.14em] text-magenta font-bold mb-1">Imperium Pass</div>
            <div className="font-display text-[13px] text-ink-3">Imperium&apos;26 · MDI Gurgaon</div>
          </div>
          <div className="font-display text-[15px] font-extrabold tracking-tight">IMPERIUM</div>
        </div>

        <div className="flex items-end justify-between gap-5 flex-wrap">
          <div className="min-w-0">
            <div className="font-display text-[26px] sm:text-[30px] font-extrabold leading-tight truncate">
              {participant.name}
            </div>
            <div className="text-ink-2 text-[15px] mb-4 truncate">{participant.institution}</div>
            <div className="text-[10px] uppercase tracking-[0.14em] text-ink-3 mb-1">Imperium ID</div>
            <div className="font-mono text-[17px] tracking-[0.08em] text-magenta">{participant.imperiumId}</div>
          </div>

          <button
            type="button"
            onClick={onExpandQr}
            aria-label="Show QR code full screen"
            className="shrink-0 bg-white p-2.5 rounded-md focus-visible:outline-magenta"
          >
            <QrGlyph value={participant.imperiumId} size={96} />
          </button>
        </div>
      </div>
    </div>
  );
}

/** Deterministic QR-style glyph. Encodes the ID visually; it is not a scannable QR. */
export function QrGlyph({ value, size = 96 }) {
  const N = 21;
  let h = 0;
  for (let i = 0; i < value.length; i++) h = (h * 31 + value.charCodeAt(i)) >>> 0;
  const cells = [];
  for (let y = 0; y < N; y++) {
    for (let x = 0; x < N; x++) {
      const finder =
        (x < 7 && y < 7) || (x >= N - 7 && y < 7) || (x < 7 && y >= N - 7);
      let on;
      if (finder) {
        const lx = x >= N - 7 ? x - (N - 7) : x;
        const ly = y >= N - 7 ? y - (N - 7) : y;
        const ring = Math.max(Math.abs(lx - 3), Math.abs(ly - 3));
        on = ring !== 2;
      } else {
        h = (h * 1103515245 + 12345) >>> 0;
        on = ((h >>> 16) & 1) === 1;
      }
      if (on) cells.push(`${x},${y}`);
    }
  }
  return (
    <svg width={size} height={size} viewBox={`0 0 ${N} ${N}`} role="img" aria-label={`Pass code ${value}`} shapeRendering="crispEdges">
      <rect width={N} height={N} fill="#fff" />
      {cells.map((c) => {
        const [x, y] = c.split(",");
        return <rect key={c} x={x} y={y} width="1" height="1" fill="#0A0A0F" />;
      })}
    </svg>
  );
}

/* --------------------------- Next-event card --------------------------- */
export function NextEventCard({ event, now }) {
  const v = venue(event.venueId);
  const start = new Date(`${event.date}T${event.startTime}:00`);
  const mins = Math.round((start - now) / 60000);
  const when =
    mins > 0 && mins < 240 ? `Starts in ${mins} min` : mins <= 0 ? "Happening now" : `${shortDay(event.date)} · ${fmtTime(event.startTime)}`;

  return (
    <div className="bg-surface border border-magenta/40 rounded-lg p-5">
      <div className="text-[10px] uppercase tracking-[0.14em] text-magenta font-bold mb-2.5">Your next event</div>
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div className="min-w-0">
          <h3 className="font-display text-[22px] font-bold leading-tight mb-1">{event.name}</h3>
          <p className="text-ink-2 text-[15px]">
            {fmtTime(event.startTime)} · {venueName(event.venueId)}
          </p>
          {v && <p className="text-ink-3 text-[13px] mt-1">{v.note}</p>}
          {event.changed && (
            <p className="mt-2.5 text-[13px] text-closing flex items-center gap-1.5">
              <span aria-hidden="true">⚠</span> This event was updated by the organisers
            </p>
          )}
        </div>
        <div className="text-right shrink-0">
          <div className="text-[13px] text-ink-3 mb-2">{when}</div>
          <Button as={Link} href={`/events/${event.slug}`} variant="secondary" size="sm">
            Details
          </Button>
        </div>
      </div>
    </div>
  );
}

export { DAY_LABELS };
