"use client";

import React, { createContext, useContext, useMemo, useReducer, useCallback, useState } from "react";
import {
  EDITION, EDITIONS, EVENTS, ANNOUNCEMENTS, SPONSORS, TRACKS, VENUES, TEAM,
  RESULTS, JUDGE, JUDGE_TEAMS, DEMO_PARTICIPANT, DEMO_CLOCKS, PRO_NIGHTS, SPONSOR_PACKAGES,
} from "@/data/imperium";
import { venueName, fmtTime, eventStart } from "@/lib/derive";

const Ctx = createContext(null);

const clone = (x) => JSON.parse(JSON.stringify(x));

const initial = {
  mode: "pre",
  editionId: "imp26",
  events: clone(EVENTS),
  announcements: clone(ANNOUNCEMENTS),
  results: clone(RESULTS),
  participant: null,
  scorecards: {},
  submittedEvents: [],
  conflicts: [],
  toasts: [],
};

let toastSeq = 0;

function reducer(state, action) {
  switch (action.type) {
    case "SET_MODE":
      return { ...state, mode: action.mode };

    case "SET_EDITION":
      return { ...state, editionId: action.editionId };

    /** The propagation spine: one organiser edit, many surfaces. */
    case "UPDATE_EVENT": {
      const { id, patch } = action;
      const before = state.events.find((e) => e.id === id);
      if (!before) return state;
      const after = { ...before, ...patch };

      const venueChanged = patch.venueId != null && patch.venueId !== before.venueId;
      const timeChanged =
        (patch.startTime != null && patch.startTime !== before.startTime) ||
        (patch.date != null && patch.date !== before.date);

      let announcements = state.announcements;
      if (venueChanged || timeChanged) {
        after.changed = true;
        after.lastChangedAt = new Date().toISOString();

        const bits = [];
        if (venueChanged) bits.push(`has moved to ${venueName(after.venueId)}`);
        if (timeChanged) bits.push(`now starts at ${fmtTime(after.startTime)}`);

        const auto = {
          id: `auto-${Date.now()}`,
          editionId: state.editionId,
          title: venueChanged ? "Venue change" : "Timing change",
          body: `${after.name} ${bits.join(" and ")}.`,
          priority: "urgent",
          eventId: after.id,
          publishedAt: new Date().toISOString(),
          autoGenerated: true,
        };
        announcements = [auto, ...state.announcements];
      }

      return {
        ...state,
        events: state.events.map((e) => (e.id === id ? after : e)),
        announcements,
        toasts: [
          ...state.toasts,
          {
            id: ++toastSeq,
            kind: "success",
            msg:
              venueChanged || timeChanged
                ? `${after.name} updated — announcement published to all surfaces`
                : `${after.name} updated`,
          },
        ],
      };
    }

    case "ADD_ANNOUNCEMENT":
      return {
        ...state,
        announcements: [{ ...action.announcement, id: `m-${Date.now()}` }, ...state.announcements],
        toasts: [...state.toasts, { id: ++toastSeq, kind: "success", msg: "Announcement published" }],
      };

    case "PUBLISH_RESULTS": {
      const { eventId, rows } = action;
      const others = state.results.filter((r) => r.eventId !== eventId);
      const added = rows.map((r, i) => ({ id: `r-${eventId}-${i}`, eventId, ...r }));
      const ev = state.events.find((e) => e.id === eventId);
      return {
        ...state,
        results: [...others, ...added],
        toasts: [...state.toasts, { id: ++toastSeq, kind: "success", msg: `Results published for ${ev ? ev.name : "event"}` }],
      };
    }

    case "CLAIM_PASS": {
      const { name, email, institution, eventIds } = action;
      const num = String(1000 + Math.floor(Math.random() * 8999));
      const inst = (institution || "IMP").replace(/[^A-Za-z]/g, "").slice(0, 3).toUpperCase() || "IMP";
      return {
        ...state,
        participant: { name, email, institution, eventIds, imperiumId: `IMP-${inst}-${num}`, readAnnouncements: [] },
        toasts: [...state.toasts, { id: ++toastSeq, kind: "success", msg: "Imperium Pass issued" }],
      };
    }

    case "DROP_PASS":
      return { ...state, participant: null };

    case "TOGGLE_MY_EVENT": {
      if (!state.participant) return state;
      const has = state.participant.eventIds.includes(action.id);
      return {
        ...state,
        participant: {
          ...state.participant,
          eventIds: has
            ? state.participant.eventIds.filter((x) => x !== action.id)
            : [...state.participant.eventIds, action.id],
        },
      };
    }

    case "MARK_READ":
      if (!state.participant) return state;
      return {
        ...state,
        participant: {
          ...state.participant,
          readAnnouncements: Array.from(new Set([...(state.participant.readAnnouncements || []), action.id])),
        },
      };

    case "SET_SCORE": {
      const { eventId, team, criterion, value } = action;
      const ev = state.scorecards[eventId] || {};
      const t = ev[team] || { scores: {}, comment: "" };
      return {
        ...state,
        scorecards: { ...state.scorecards, [eventId]: { ...ev, [team]: { ...t, scores: { ...t.scores, [criterion]: value } } } },
      };
    }

    case "SET_COMMENT": {
      const { eventId, team, comment } = action;
      const ev = state.scorecards[eventId] || {};
      const t = ev[team] || { scores: {}, comment: "" };
      return { ...state, scorecards: { ...state.scorecards, [eventId]: { ...ev, [team]: { ...t, comment } } } };
    }

    case "SUBMIT_SCORES":
      return {
        ...state,
        submittedEvents: Array.from(new Set([...state.submittedEvents, action.eventId])),
        toasts: [...state.toasts, { id: ++toastSeq, kind: "success", msg: "Scores submitted and locked" }],
      };

    case "TOGGLE_CONFLICT":
      return {
        ...state,
        conflicts: state.conflicts.includes(action.eventId)
          ? state.conflicts.filter((x) => x !== action.eventId)
          : [...state.conflicts, action.eventId],
      };

    case "TOAST":
      return { ...state, toasts: [...state.toasts, { id: ++toastSeq, kind: action.kind || "info", msg: action.msg }] };

    case "DISMISS_TOAST":
      return { ...state, toasts: state.toasts.filter((t) => t.id !== action.id) };

    case "RESET":
      return { ...clone(initial), mode: state.mode };

    default:
      return state;
  }
}

export function ImperiumProvider({ children }) {
  const [state, dispatch] = useReducer(reducer, initial);
  const [notified, setNotified] = useState([]);

  const now = useMemo(() => new Date(DEMO_CLOCKS[state.mode]), [state.mode]);

  const eventById = useCallback((id) => state.events.find((e) => e.id === id) || null, [state.events]);
  const eventBySlug = useCallback((slug) => state.events.find((e) => e.slug === slug) || null, [state.events]);

  const myEvents = useMemo(() => {
    if (!state.participant) return [];
    return state.participant.eventIds
      .map((id) => state.events.find((e) => e.id === id))
      .filter(Boolean)
      .sort((a, b) => eventStart(a) - eventStart(b));
  }, [state.participant, state.events]);

  const nextEvent = useMemo(() => {
    if (!myEvents.length) return null;
    const upcoming = myEvents.filter((e) => new Date(`${e.date}T${e.endTime}:00`) >= now);
    return upcoming[0] || myEvents[myEvents.length - 1];
  }, [myEvents, now]);

  // Results are only public once the fest has actually happened.
  const publicResults = useMemo(
    () => (state.mode === "pre" ? [] : state.results),
    [state.mode, state.results]
  );

  const resultsFor = useCallback(
    (eventId) => publicResults.filter((r) => r.eventId === eventId).sort((a, b) => a.position - b.position),
    [publicResults]
  );

  const loadDemoParticipant = useCallback(() => {
    const ids = DEMO_PARTICIPANT.eventSlugs
      .map((s) => (state.events.find((e) => e.slug === s) || {}).id)
      .filter(Boolean);
    dispatch({
      type: "CLAIM_PASS",
      name: DEMO_PARTICIPANT.name,
      email: DEMO_PARTICIPANT.email,
      institution: DEMO_PARTICIPANT.institution,
      eventIds: ids,
    });
  }, [state.events]);

  const notifyMe = useCallback((id) => setNotified((n) => (n.includes(id) ? n : [...n, id])), []);

  const value = {
    ...state,
    results: publicResults,
    allResults: state.results,
    now,
    edition: EDITION,
    editions: EDITIONS,
    tracks: TRACKS,
    venues: VENUES,
    sponsors: SPONSORS,
    sponsorPackages: SPONSOR_PACKAGES,
    team: TEAM,
    proNights: PRO_NIGHTS,
    judge: JUDGE,
    judgeTeams: JUDGE_TEAMS,
    dispatch,
    eventById,
    eventBySlug,
    myEvents,
    nextEvent,
    resultsFor,
    loadDemoParticipant,
    notified,
    notifyMe,
  };

  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}

export function useImperium() {
  const v = useContext(Ctx);
  if (!v) throw new Error("useImperium must be used inside ImperiumProvider");
  return v;
}
